name: Keep Alive - Ping Supabase

on:
  schedule:
    # Cette ligne planifie l'exécution toutes les 10 minutes
    - cron:  '*/10 * * * *'
  workflow_dispatch: # Permet de lancer manuellement le workflow depuis l'onglet "Actions"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping my Supabase project
        run: |
          curl -X GET "https://https://rmrxsaiianffhpxpntws.supabase.co/rest/v1/profiles?select=id&limit=1" \
               -H "apikey: ${{ sb_publishable_NCr1RgEcA4MaWqMpWhlKaw_6wp2PZJE}}"
